-- 1. Create Tablespace
CREATE TABLESPACE TBL_SP 
DATAFILE 'TBL_SPX.dbf' SIZE 10M AUTOEXTEND ON NEXT 2M MAXSIZE 40M,
'TBL_SP2.dbf' SIZE 15M;

-- 2. Rename File
ALTER DATABASE RENAME FILE 'TBL_SPX.dbf' TO 'TBL_SP1.dbf';

-- 3. Create Stored Function
CREATE OR REPLACE FUNCTION FN_VERIF(user_name VARCHAR, password VARCHAR, old_password VARCHAR) 
RETURN BOOLEAN IS
BEGIN
  -- Check password conditions
  IF password LIKE '%root%' OR password LIKE '%admin%' OR password LIKE '%oracle%' THEN
    RETURN FALSE;
  ELSIF NOT REGEXP_LIKE(password, '[A-Z]') OR NOT REGEXP_LIKE(password, '[a-z]') THEN
    RETURN FALSE;
  END IF;
  RETURN TRUE;
END;

-- 4. Create User Profile
CREATE PROFILE PRF_SP LIMIT 
SESSIONS_PER_USER 2 
IDLE_TIME 20 
PASSWORD_LIFE_TIME 60 
PASSWORD_VERIFY_FUNCTION FN_VERIF;

-- 5. Create User
CREATE USER USER_SP IDENTIFIED BY password 
DEFAULT TABLESPACE TBL_SP 
QUOTA UNLIMITED ON TBL_SP 
PROFILE PRF_SP 
ACCOUNT LOCK;

GRANT CREATE SESSION TO USER_SP;
GRANT INSERT, UPDATE ON HR.JOB_HISTORY TO USER_SP;
GRANT CREATE TRIGGER TO USER_SP;
GRANT CREATE PROCEDURE TO USER_SP;

-- 6. Set Up Auditing
AUDIT CREATE USER BY USER_SP;
AUDIT CREATE INDEX BY USER_SP;
AUDIT DROP SYNONYM BY USER_SP;
AUDIT UPDATE, DELETE ON HR.DEPARTMENTS;

-- 7. Create Function for Table Size
CREATE OR REPLACE FUNCTION GET_TABLE_SIZE(table_name VARCHAR) 
RETURN NUMBER IS
BEGIN
  -- Logic to calculate table size
END;

-- 8. Create Procedure for User Privileges
CREATE OR REPLACE PROCEDURE SHOW_USER_PRIVILEGES(user_name VARCHAR) IS
BEGIN
  -- Logic to display user privileges
END;

-- 9. Write Audit Instructions
-- Based on the results of the audit options provided.
